spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包
    url: jdbc:mysql://47.106.131.115:3306/comic?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useAffectedRows=true&serverTimezone=Asia/Shanghai              # 数据库名称
    username: lesinguser
    password: Lesing123++
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 10000
    jedis:
      pool:
        max-idle: 300
        max-wait: -1
        min-idle: 20

logging:
  level:
    com:
      woomics:
        provider:
          mapper: debug  #开启mybatis日志

info:
  app.name: woomics-provider9001
  company.name: localhost
  build.artifactId: $project.artifactId$
  build.version: $project.version$
  
env: aaaad1
